#!/bin/sh
wget https://snjpn.net/wp-content/uploads/2017/07/demon.jpg -O ./images/kogure.jpeg
wget https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1D45jZDIgvDHyTSoMcVkmVxxNqLufpe58PpdluAyjyQTJscV8pQ -O ./images/bootstrap.jpg
